// Generated by CoffeeScript 1.8.0
(function() {
  var $, banner, bannerWidth, isHomePage, setBannerPosition;

  $ = jQuery;

  banner = $('.banner img');

  if (!banner.length) {
    return;
  }

  isHomePage = $('body.home').length > 0;

  bannerWidth = banner.width();

  setBannerPosition = function() {
    var windowWidth;
    if (isHomePage) {
      return;
    }
    windowWidth = $(window).width();
    if (windowWidth < 1000) {
      windowWidth = 1000;
    }
    return banner.each(function() {
      var $el;
      $el = $(this);
      return $el.css('left', -1 * (bannerWidth - windowWidth) / 2 + 'px');
    });
  };

  $(window).on('resize', setBannerPosition);

  setBannerPosition();

}).call(this);
