// Generated by CoffeeScript 1.8.0
(function() {
  var $, country;

  $ = jQuery;

  country = $('.country select');

  country.on('change', function() {
    var $this, countryUrl;
    $this = $(this);
    countryUrl = $this.val();
    if (countryUrl) {
      return window.location = countryUrl;
    }
  });

}).call(this);
