// Generated by CoffeeScript 1.8.0
(function() {
  var $, dropdown;

  if (Modernizr.csspointerevents) {
    return;
  }

  $ = jQuery;

  dropdown = $('.dropdown');

  dropdown.on('click', function(e) {
    var $this, select;
    $this = $(this);
    if (e.offsetX < $this.width() - 30) {
      return true;
    }
    select = $this.find('select');
    select.one('blur', function() {
      return $(this).attr('size', 1);
    });
    select.attr('size', select.find('option').length);
    select.focus();
    return false;
  });

}).call(this);
