// Generated by CoffeeScript 1.7.1
(function() {
  var $, carousel, carouselDefaultHeight, carouselItems, container, shrinkHomeBanners;

  $ = jQuery;

  container = $('.home .features');

  container.append('<div class="gutter">');

  container.masonry({
    itemSelector: '.widget',
    gutter: '.gutter',
    transitionDuration: 0
  });

  carousel = $('.home .banner');

  carouselItems = carousel.find('.item');

  carouselDefaultHeight = null;

  shrinkHomeBanners = function() {
    var windowWidth;
    windowWidth = $(window).width();
    return carouselItems.each(function() {
      var containerSizeRatio, contentWidth, contents, el, height, imageSizeRatio, width;
      el = $(this);
      contentWidth = el.data('content-width');
      containerSizeRatio = carouselDefaultHeight / contentWidth;
      contents = el.find('img');
      imageSizeRatio = contents.attr('height') / contents.attr('width');
      if (windowWidth < contentWidth) {
        el.height(windowWidth * containerSizeRatio);
      } else {
        el.height(carouselDefaultHeight);
      }
      height = el.height();
      width = height / imageSizeRatio;
      contents.height(height);
      contents.width(height / imageSizeRatio);
      return contents.css('left', -1 * (width - windowWidth) / 2 + 'px');
    });
  };

  carousel.owlCarousel({
    navigation: true,
    slideSpeed: 300,
    paginationSpeed: 400,
    singleItem: true,
    navigation: false,
    afterInit: function() {
      carouselDefaultHeight = carousel.height();
      return shrinkHomeBanners();
    },
    autoPlay: 10000,
    stopOnHover: true
  });

  carousel.find('.item').on('click', function() {
    return carousel.trigger('owl.next');
  });

  $(window).on('resize', shrinkHomeBanners);

  if ($("#optincta").length) {
    $(".container").css("padding-top", "40px");
    $(".container").css("transform", "none");
    $("#optincta").show();
    $(".optin-close").click(function() {
      $("#optincta").slideUp("slow", function() {
        $(".container").css("padding-top", "0px");
        $(".container").css("transform", "translate3d(0, 0, 0)");
      });
    });
  }

}).call(this);


//# sourceMappingURL=home.map
