// Generated by CoffeeScript 1.8.0
(function() {
  var $, menu, menuTrigger, pageContainer;

  $ = jQuery;

  menuTrigger = $('.menu-button');

  pageContainer = $('.container');

  menu = $('body > nav');

  menuTrigger.on('click', function() {
    pageContainer.toggleClass('nav-open');
    return menu.toggleClass('active');
  });

}).call(this);
