// Generated by CoffeeScript 1.8.0
(function() {
  var $;

  $ = jQuery;

  $('select[name="country"]').change(function() {
    if ($(this).val() === 'CA') {
      $('#GB').hide();
      $('#GB input').prop('required', false);
      $('#CA').show();
      return $('#CA input').prop('required', true);
    } else {
      $('#CA').hide();
      $('#GB').hide();
      $('#CA input').prop('required', false);
      return $('#GB input').prop('required', false);
    }
  });

}).call(this);
