// Generated by CoffeeScript 1.8.0
(function() {
  var $, filter, filterElements, filterResources, filters, more_button, more_resources;

  $ = jQuery;

  filterElements = $('.resource-filter:not(.inline) select');

  filters = {};

  filterResources = function() {
    var href, query;
    filterElements.each(function() {
      var $this, filter, type;
      $this = $(this);
      type = $this.prop('name');
      filter = $this.val();
      if (filter) {
        return filters[type] = filter;
      }
    });
    href = location.pathname.replace(/page\/\d+\//, '');
    if (query = $.param(filters)) {
      href += '?' + query;
    }
    return location.href = href;
  };

  filterElements.on('change', filterResources);

  more_button = $('.resources ~ .pagination a');

  more_resources = $('.resources.more');

  more_button.on('click', function() {
    if (more_resources.length) {
      more_button.parents('.pagination').hide();
      more_resources.slideDown();
      return false;
    }
  });

  filter = $('.resource-filter.inline select');

  filter.on('change', function() {
    var all_resources, value;
    value = filter.val();
    $('.pagination').hide();
    $('.resources.more').show();
    all_resources = $('.resource');
    if (value) {
      all_resources.hide();
      return all_resources.filter("." + value).show();
    } else {
      return all_resources.show();
    }
  });

}).call(this);
