// Generated by CoffeeScript 1.8.0
(function() {
  var $, field, searchForm;

  $ = jQuery;

  searchForm = $('.search');

  field = searchForm.find('input');

  field.on('focus', function() {
    return searchForm.addClass('open');
  });

  field.on('blur', function() {
    return searchForm.removeClass('open');
  });

}).call(this);
